export const PERMISSIONS = Object.freeze({
    CREATE_EMPLOYEE: 'CREATE_EMPLOYEE',
    VIEW_EMPLOYEE: 'VIEW_EMPLOYEE',
    UPDATE_EMPLOYEE: 'UPDATE_EMPLOYEE',
    DELETE_EMPLOYEE: 'DELETE_EMPLOYEE',
    CREATE_USER: 'CREATE_USER',
    VIEW_USER: 'VIEW_USER',
    UPDATE_USER: 'UPDATE_USER',
    DELETE_USER: 'DELETE_USER',
});